server:
  port: 8080
  servlet:
    context-path: /api

spring:
  data:
    web:
      pageable:
        default-page-size: 10

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect

  mail:
    host: mail.privateemail.com
    port: 587
    username: noreply@nullhire.com
    password: E$pRZ2H*rd3f5$
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  messages:
    basename: i18n/messages
    encoding: UTF-8
  sql:
    init:
      platform: postgres
      mode: always

logging:
  level:
    com:
      opdev: INFO
    org:
      hibernate: INFO
      springframework:
        security: DEBUG

security:
  aes:
    secret: "3WTR3Ep7MItSFduTZvgyQQ=="

nullhire:
  profile-images-dir: https://api.nullhire.com/images
  base-url: https://api.nullhire.com
  domain: https://nullhire.com
  allowed-origins: https://nullhire.com,https://admin.nullhire.com

import:
  local:
    data: false