server:
  port: 8080
  servlet:
    context-path: /api

spring:
  data:
    web:
      pageable:
        default-page-size: 10

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: ""

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  mail:
    host: mail.privateemail.com
    port: 587
    username: noreply@nullhire.com
    password: ${NOREPLY_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  messages:
    basename: i18n/messages
    encoding: UTF-8

logging:
  level:
    com:
      opdev: INFO
    org:
      hibernate: INFO
      springframework:
        security: DEBUG

security:
  aes:
    secret: ${AES_SECRET}

nullhire:
  profile-images-dir: /Users/nikolapantelic/Documents/images
  base-url: http://localhost:8080
  domain: http://localhost:4200
  allowed-origins: http://localhost:4200,null
  google:
    client-id: "533125345294-queakbtfu0dbros8hlhirk1o1ct427m4.apps.googleusercontent.com"
    cookie:
      secure: false
      domain: "localhost"
      validity-in-seconds: 30

import:
  local:
    data: true

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus
          - heapdump