logging:
    level:
        com:
            opdev: INFO
        org:
            hibernate: INFO
            springframework:
                security: DEBUG

server:
    port: 8080
    servlet:
        context-path: /api

security:
    aes:
        secret: "3WTR3Ep7MItSFduTZvgyQQ=="

spring:
    data:
        web:
            pageable:
                default-page-size: 10

    datasource:
        driverClassName: org.h2.Driver
        password: ""
        url: jdbc:h2:mem:testdb
        username: sa
    h2:
        console:
            enabled: true
            path: /h2-console
            settings:
                trace: false
                web-allow-others: false

    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update

    mail:
        host: mail.privateemail.com
        password: E$pRZ2H*rd3f5$
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
        username: noreply@nullhire.com

    messages:
        basename: i18n/messages
        encoding: UTF-8

    profiles:
        active: dev
        # active: prod
        # active: test

import:
    local:
        data: true